#!/usr/bin/env bash
if [ "$@" ]
then
    addr="$(echo "$*" | head -c 9)"
    dunstify "swapping to $addr"
    hyprctl dispatch focuswindow address:${addr} > /dev/null
else
    state="$(hyprctl -j clients)"
    active_window="$(hyprctl -j activewindow)"
    current_addr="$(echo "$active_window" | gojq -r '.address')"
    
    echo "$( 
        (hyprctl -j clients) | 
        gojq -r '.[] | select(.monitor != -1 ) | "\(.address) [\(.workspace.name)] - \(.title) (\(.class))"' |
        sed "s|$current_addr|focused ->|" |
        sort -r )"
fi

